config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

app/models/completion_date.rb
class CompletionDate < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  has_many :completion_dates
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @task = Task.where(category_id: @category)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: 'category was successfully destroyed.'
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
    @category = Category.find(params[:category_id])
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(params[:category_id])
    @task.category_id = params[:category_id]

    if @task.save
      redirect_to @category, notice: 'task was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to categories_path, notice: 'task was successfully destroyed.'
  end

  def edit
    @category = Category.find(params[:category_id])
    @task = Task.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to categories_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end
end

#  t.string :name
#     t.references :category, null: false, foreign_key: true
#     t.float :compound_rate
#     t.integer :compound_time_block
#     t.integer :start_date
#     t.integer :goal_end_date
#     t.integer :goal_success_rate
#     t.integer :rep_time_block
#     t.integer :reps_per_time_block

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<h1>Editing</h1>

<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to "Categories", categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<h3>What areas of your life are focused on improving?</h3>
<div class = "categories">
  <ul>
    <% @categories.each do |cat| %>
    <li>
      <ul><h6><%= link_to "#{cat.name}", category_path(cat)%></h6>
      <li><p>tasks: <%= Task.where(category_id: cat).count %></p></li>
      </ul>
    </li>
    <% end %>
  </ul>
</div>
<br>
<%= link_to "New Category", new_category_path%>

app/views/categories/new.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to "Categories", categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<h6>There personal statement e.g. their why</h6>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Excepturi cumque vel quod qui blanditiis fugiat atque earum labore! Error distinctio quae inventore nobis rerum voluptatibus tenetur quasi natus facere illum?</p>
<% @task.each do |task| %>
  <%= link_to "#{task.name}", category_task_path(@category, task)%>
<% end %>
<%= link_to 'Edit', edit_category_path(@category) %>
<%= link_to 'Delete this category', @categories, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to "Add a Task", new_category_task_path(@category)%>
<%= link_to "Categories", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skilltracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Editing</h1>

<%= simple_form_for [@category, @task] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to "Categories", categories_path %>

app/views/tasks/new.html.erb
<%= simple_form_for [@category, @task] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to "Categories", categories_path %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p>form with adjustable settings and display graph</p>
<%= link_to 'Edit', edit_category_task_path(category_id = params[:category_id], id = params[:id]) %>
<%= link_to 'Delete this task', @categories, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to "Categories", categories_path %>